import type { Metadata } from "next"
import { Figtree, Urbanist } from "next/font/google"
import React from "react"
import "./globals.css"
import Navigation from "@/components/Navigation"
import Announcement from "@/components/Announcement"

const figtree = Figtree({
    subsets: ["latin"],
    variable: "--font-figtree",
    display: "swap"
})

const urbanist = Urbanist({
    subsets: ["latin"],
    variable: "--font-urbanist",
    display: "swap"
})

export const metadata: Metadata = {
    title: "Fametonic",
    description: "Generated by create next app"
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang='en'>
            <body className={`${urbanist.variable} ${figtree.variable} flex min-h-screen flex-col antialiased`}>
                <Announcement />
                <Navigation />
                <main className='flex flex-1 flex-col'>{children}</main>
            </body>
        </html>
    )
}
